name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout code
        uses: actions/checkout@v2

      - name: â¤´ Upload .env file
        uses: actions/upload-artifact@v2
        with:
          name: env-file
          path: .env

      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@${{ secrets.TAG }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: â¤µ Download .env file
        uses: actions/download-artifact@v2
        with:
          name: env-file
          path: .

      - name: ğŸ“¦ Build Docker image
        run: |
          docker build \
            --build-arg ENV_FILE=.env \
            --pull \
            --cache-from ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.TAG }} \
            --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.TAG }} \
            --file Dockerfile .
      - name: ğŸš€ Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.TAG }}
